// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonSpaceshipsGame.Models.Database;

namespace PersonSpaceshipsGame.Migrations
{
    [DbContext(typeof(CardGameContext))]
    [Migration("20201108155521_addedCardType")]
    partial class addedCardType
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PersonSpaceshipsGame.Models.Cards.Person.PersonCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CardType")
                        .HasColumnName("CardType1")
                        .HasColumnType("int");

                    b.Property<string>("CardTypeString")
                        .HasColumnName("CardType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Mass")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("PersonCards");
                });

            modelBuilder.Entity("PersonSpaceshipsGame.Models.Cards.Spaceships.SpaceshipCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CardType")
                        .HasColumnName("CardType1")
                        .HasColumnType("int");

                    b.Property<string>("CardTypeString")
                        .HasColumnName("CardType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CrewCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("SpaceshipCards");
                });

            modelBuilder.Entity("PersonSpaceshipsGame.Models.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("PersonSpaceshipsGame.Models.Cards.Person.PersonCard", b =>
                {
                    b.HasOne("PersonSpaceshipsGame.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");
                });

            modelBuilder.Entity("PersonSpaceshipsGame.Models.Cards.Spaceships.SpaceshipCard", b =>
                {
                    b.HasOne("PersonSpaceshipsGame.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");
                });
#pragma warning restore 612, 618
        }
    }
}
